In [1]:
import pandas as pd

In [2]:
monks1_train = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/monks-problems/monks-1.train', header=None)

In [5]:
monks1_train = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/monks-problems/monks-1.train', 
                           header=None, sep=" ", skipinitialspace=True)

In [6]:
monks1_train.head()

,0,1,2,3,4,5,6,7
0,1,1,1,1,1,3,1,data_5
1,1,1,1,1,1,3,2,data_6
2,1,1,1,1,3,2,1,data_19
3,1,1,1,1,3,3,2,data_22
4,1,1,1,2,1,2,1,data_27


In [7]:
X_train = monks1_train.iloc[:,:6]

In [8]:
X_train.head()

,0,1,2,3,4,5
0,1,1,1,1,1,3
1,1,1,1,1,1,3
2,1,1,1,1,3,2
3,1,1,1,1,3,3
4,1,1,1,2,1,2


In [11]:
y_train = monks1_train.iloc[:,6]

In [13]:
y_train

0      1
1      2
2      1
3      2
4      1
      ..
119    2
120    2
121    2
122    2
123    2
Name: 6, Length: 124, dtype: int64

In [15]:
from neuralnet import NeuralNetMLP

In [16]:
nn = NeuralNetMLP(n_hidden=100,
                  l2=0.01,
                  epochs=200,
                  eta=0.0005,
                  minibatch_size=100,
                  shuffle=True,
                  seed=1)

In [18]:
nn._onehot(X_train,17)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [19]:
one-hot = nn._onehot(X_train,17)

SyntaxError: cannot assign to operator (<ipython-input-19-93da47450354>, line 1)

In [20]:
one_hot = nn._onehot(X_train, 17)

In [21]:
one_hot.head()

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [22]:
one_hot

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [28]:
one_hot[0]

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
one_hot[1]

array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
#array of arrays